# Introduction to Python

This is a very brief, surface-level intro to Python that will let you experiment with the basic data types and commands. Don't worry if everything is not entirely clear, we'll keep using these concepts throughout the sessions and they will become more familiar. This is meant to be a fun excercise that will make you want to keep programming!

## Basics

### Data Types

Python can handle many types of data represented by objects. Four basic data types that you should know are:
- `int` (2)
- `float` (3.5)
- `str` ("hello")
- `bool` (`True`, `False`)

Both single `'` or double `"` quotes are valid in Python. 

You can test the type of an object using `type(object)`. We can use this to check the types of various objects below:

In [ ]:
type(4), type(2.7), type("Python"), type(True)

(int, float, str, bool)

Exercise: Now use `type()` to check the types of the following objects:

*   38.5
*   38.
*   38
*   "38"

Note that only the final line is displayed so try to write the code on one line as above. Alternatively you can use the `print()` function to display the outputs

In [ ]:
# Please write your code below
type(38.5), type(38.), type(38), type("38")

(float, float, int, str)

You can also assign objects to variables by putting the variable name on the left, followed by an equal sign, followed by a value, as in
`my_var = "a string"`

Note that variable names cannot contain a space, and certain strings are reserved by the language and cannot be used as variable names.

Here we assign a value of `0.3` to a variable called `x`, then check the type.

In [ ]:
x = 0.3
type(x)

float

### Numeric Operations

We can do all the usual things with numbers, including addition (`+`), subtraction (`-`), multiplication (`*`), and division (`/`). We also have exponentiation (`**`), integer division (`//`), and modulus (`%`).

Exercise: Try playing around with the operations so you understand what they do. If you are unsure of the order of operations, use parentheses

In [ ]:
# Change the values and operations below, or create new expressions
print(21%2.3)

0.3000000000000016

Of course, this can also be done with variables

In [ ]:
x = 50
y = 23
z = x + y
print(x, y, z)

50 23 73

Note that variable assignment can be self referential. To increase the value of `x` by 1, we can write

In [ ]:
x = x + 1
print(x)

55

This is so common, in fact, that there is a shorthand for it

In [ ]:
x += 1
print(x)

166

This shorthand also exists for many other basic operators.

Exercise: Try it below

In [ ]:
# Change the values and operators. Ask if the result is unintuitive
x = 20
x %= 3
print(x)

2

Polymorphism is the idea that the meaning of an operation, such as + and *, depends on the objects being operated on

For example, here `+` is referred to as “concatenation” and `*` as “repetition”

In [ ]:
print("Barn" + "yard")
print("Hello"*3)

Barnyard
HelloHelloHello

### Casting

Sometimes we want to change the data type of an object. For example, we might get the strings `"2"` and `"5"` as input, but we want to treat them as numbers and add them. If we just add them, we don't get the desired result:

In [ ]:
input_1 = "2"
input_2 = "5"
input_1 + input_2

'25'

We can convert them to the `int` type through whats called casting. This tells the program to treat the objects as if they were a different type

In [ ]:
int(input_1) + int(input_2)

7

This does have its limits, as some objects cannot be converted. For example, this returns an error

In [ ]:
int("a string")

ValueError: ignored

## Data Structures

When we have a collection of several objects, there are many ways to organize them. These types of objects that hold data are called "data structures." Two basic properties are whether they are ordered, and whether they are mutable. Objects in an ordered data structure has a definite position, ie first, second, third etc. An object or data structure is said to be "mutable" if its value can change after creation. In some applications it is desirable for an object to hold a consistent value and so immutability is desired.

A few of the most commonly used data structures are
*   Lists: Ordered, mutable
*   Tuples: Ordered, immutable
*   Sets: Unordered, mutable, no duplicates
*   Dictionary: unordered, mutable, stores (key, value) pairs

Typically we will be using lists to store most objects.

### List examples

Lists are exactly what you'd expect them to be; an ordered collection of objects. In theory there is no restriction on what objects can be put into a list. They can have different types, and can themselves be lists. However, in practice we will want the elements to share a type so they are easier to work with. To create a list, use an open bracket `[` to denote the start and and a close bracket `]` to denote the end, and separate elements with a comma `,`.

In [ ]:
type(["a", "list", "of", "strings"])

list

In [ ]:
type([2, "a very diverse list", True, 0.33, [1, 2, 3]])

list

Elements of the list can be accessed using the syntax `list_name[index]`. Note that Python is a 0-indexed language, so `list_name[0]` returns the value of the first element. Try to change the index to retrieve the word `"fox"`

In [ ]:
my_list = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
my_list[2]

'brown'

We can also change the values in a list through assignment

In [ ]:
list_of_numbers = [0, 1, 2]
list_of_numbers[0] = "a string"
list_of_numbers

['a string', 1, 2]

To get the length of a list, use `len()`

In [ ]:
my_list = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
len(my_list)

9

### Tuple examples

Tuples are similar to lists, and are represented as a sequence separated by `,` surrounded by parentheses `()`. They also support indexing to retrieve elements, but differ from lists in that you cannot change the values through indexing.

In [ ]:
type((1, 2, "a", "b"))

tuple

In [ ]:
my_tuple = ("the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog")
my_tuple[0]

'the'

Trying to assign values to a tuple will result in an error

In [ ]:
tuple_of_numbers = (0, 1, 2)
tuple_of_numbers[0] = "a string"

TypeError: ignored

Strings can also be treated as tuples. For example, you can index into them and find the length, but you cannot assign values

In [ ]:
my_string = "The sky is blue"
print(my_string[2])
print(len(my_string))

e
15

### Set examples

Sets are also collections of objects, but they are unordered and do not contain duplicates. They are represented as a sequence separated by `,` surrounded by curly braces `{}`.

In [ ]:
type({"peanut", "walnut", "pecan"})

set

In [ ]:
my_set = {"peanut", "walnut", "pecan"}
my_set.add("cashew")
print(my_set)

{'peanut', 'cashew', 'walnut', 'pecan'}

Adding a duplicate does nothing

In [ ]:
my_set = {"peanut", "walnut", "pecan"}
my_set.add("peanut")
print(my_set)

{'peanut', 'walnut', 'pecan'}

Because they are unordered, you cannot index into a set

In [ ]:
my_set = {"peanut", "walnut", "pecan"}
my_set[0]

TypeError: ignored

Sets support many different operations with other sets, such as union and intersection

In [ ]:
my_set_1 = {1, 2, 3, 4, 5}
my_set_2 = {4, 5, 6, 7}
print(my_set_1.union(my_set_2))
print(my_set_1.intersection(my_set_2))

{1, 2, 3, 4, 5, 6, 7}
{4, 5}

### Dictionary examples

Dictionaries store (key, value) pairs. For example, suppose that we wanted to store what element each symbol on the periodic table corresponds to. For brevity we will only consider the first 4 elements. There are several ways to construct a dictionary. The first way would be to list out each key value pair separated by a colon `:`, inside curly braces `{}`. Note that the order does not matter, and the following are equivalent:

In [ ]:
periodic_dict = {"H": "hydrogen", "He": "helium", "Li" : "lithium", "Be": "beryllium"}
periodic_dict = {"Be": "beryllium", "Li" : "lithium", "He": "helium", "H": "hydrogen"}

Now we can access the values inside as follows:

In [ ]:
periodic_dict["Be"]

'beryllium'

Alternatively, we can start by initializing an empty dictionary, and assign values to keys:

In [ ]:
another_periodic_dict = dict()
another_periodic_dict["H"] = "hydrogen"
another_periodic_dict["He"] = "helium"
another_periodic_dict["Li"] = "lithium"
another_periodic_dict["Be"] = "beryllium"

We can also change the values already in the dictionary

In [ ]:
another_periodic_dict["H"] = "Heisenberg"
another_periodic_dict["H"]

'Heisenberg'

Note that the objects being used as keys and values do not all have to be the same type. For example, we can use a dictionary to store information about a person.

Exercise: Complete the profile by adding some of your own values, such as age, favorite food, etc.

In [ ]:
Person_1 = dict()
Person_1["first name"] = "John"
Person_1["last name"] = "Doe"
Person_1["age"] = 25
Person_1["favorite color"] = "blue"

Exercise: Now suppose that three years have passed. Write code that increments the value corresponding to the `"age"` key by 3

In [ ]:
# Write your code below
Person_1["age"] += 3
Person_1["age"]

28

## Comparators

There are 8 comparison operations in Python, which are most commonly used for numeric types
- `x` < `y`
- `x` <= `y`
- `x` > `y`
- `x` >= `y`
- `x` == `y`
- `x` != `y`
- `is`
- `is not`

These can also be used for other types, like sequences, where comparisons are done element wise.

In [ ]:
# Try it out!
print(4 > 10)
print(4 == 4)

False
True

The `is` operator is similar to the `==` operator, but checks object equality instead of value equality. We typically care about value equality, and will be mostly using `==`. Here is an example of when the two are different. Even though the lists store the same values, they are different objects. Modifying one list would not change the other.

In [ ]:
list_1 = ["a", "b"]
list_2 = ["a", "b"]
print(list_1 == list_2)
print(list_1 is list_2)

True
False

## Conditional Statements

Conditional statements are a way for your code to make decisions. Depending on whether the condition is `True` or `False`, a different section of code will be executed. The syntax for an `if` statement looks like

```
if condition:
    code to be executed if condition is True

code that will be executed regardless of whether condition is True or False
```

For example, the following code checks if `a` is larger than `b`, and if it is, prints the string `a is larger than b`. Try changing the values of `a` and `b` around

In [ ]:
a = 5
b = 2

if a > b:
    print("a is larger than b")

print("this line is always printed")

a is larger than b
this line is always printed

Here are a few details to keep in mind when writing `if` statements:
*   The condition (`a > b` in this case) should always be followed by a colon (`:`)
*   All the code you want to be executed if the condition is true should be indented once relative to the condition
*   Once you have written all the code inside the `if` statement, unindent your code to signal you have exited the conditional

In many cases, there is also specific code that you want to execute if the condition is `False`. Then we can use an `if ... else ...` statement. The syntax is similar.

In [ ]:
a = 5
b = 7

if a > b:
    print("a is larger than b")
elif a < b:
    print("a is less than b")
else:
    print("a is equal to b")

print("this line is always printed")

a is less than b
this line is always printed

Exercise: Try using a conditional statement to print `a is even` if  `a` is divisible by 2, and `a is odd` otherwise

In [ ]:
a = 10
# Write your code below
if a%2==1:
    print("a is odd")
else:
    print("a is even")

a is even

If there are more two possible branches, we can use `elif` statements, which are short for "else if". For example, suppose a park has different prices for kids, adults, and seniors. To print the price, we can do the following:

In [ ]:
age = 30

if age < 18:
    print("The price is 5 dollars")
elif age < 65:
    print("The price is 15 dollars")
else:
    print("The price is 0 dollars")

We can also combine multiple conditions in 1. For example, to check if a number is divisible by 2 but not 3, we can use the following code:

In [ ]:
a = 3
if a%2 == 0 and a%3 != 0:
    print("a is divisible by 2 but not 3")

Exercise: Given a variable `a`, print which of the following categories it belongs to using conditional statements:

*   Not divisible by 2 or 3 
*   Divisible by 2 but not 3
*   Divisible by 3 but not 2
*   Divisible by 2 and 3

In [ ]:
a = 35
# Write your code below
if a%2 != 0 and a%3 != 0:
    print('A is not divisible by 2 or 3')
elif a%2 == 0 and a%3 != 0:
    print('a is divisible by 2 but not 3')
elif a%2 != 0 and a%3 == 0:
    print('a is divisible by 3 but not 2')
elif a%2 == 0 and a%3 == 0:
    print('a is divisible by 2 and 3')

if a%2==0:
    if a%3==0:
        print('a is divisible by 2 and 3')
    else:
        print('a is divisible by 2 and but not 3')
else:
    if a%3==0:
        print('a is not divisible by 2 but divisible by 3')
    else:
        print('a is not divisible by 2 or 3')

A is not divisible by 2 or 3

In [ ]:
if a%2 != 0 and a%3 != 0:
    print('A is not divisible by 2 or 3')
else if a%2 == 0 and a%3 != 0:
    print('a is divisible by 2 but not 3')
else:
    # do nothing

## Loops and iterators

### For loops

It is extremely common to perform operations on a collection of objects, and this is where we use loops. For example, suppose we want to print out each item in a list. This can be achieved using a `for` loop:

In [1]:
my_list = ["apple", "banana", "cherry"]
for x in my_list:
    print(x)

apple
banana
cherry

The syntax used `for` loops is similar to that of an `if` statement.

```
for my_var in my_iterable:
    code to be executed with my_var

code that will be executed afterwards
```

The `for` statment is ended by a colon `:` and the body of the `for` statment is indented. The next piece that you want to pay attention to is

`my_var in my_iterable`

This means that we will go through each item in `my_iterable`, which is typically a list, assign its value to the variable `my_var`, and run the code in the body of the loop, which in the above example prints the value.

Exercise: Use a for loop to print all the items in the following list of numbers

In [2]:
list_of_numbers = [1, 6, 2, 7, 2]
# Write your code below
for i in list_of_numbers:
    print(i)

1
6
2
7
2

Exercise: Use a `for` loop to add all the items in the following list of numbers, then print the result. You can create your own variable to hold intermediate results

In [7]:
list_of_numbers = [1, 6, 2, 7, 2]
# Write your code below
sum_of_list = 0
for list_element in list_of_numbers:
    sum_of_list += list_element
print(sum_of_list)

18

You can put `if` statements inside a `for` loop (and vice versa).

Exercise: Use a `for` loop to iterate through the list of numbers and if it is even print the number

In [4]:
list_of_numbers = [1, 6, 2, 7, 2]
# Write your code below
for i in list_of_numbers:
    if i%2 == 0:
        print(i)

6
2
2

Exercise: Instead of printing all the even numbers, create a set of all unique even numbers and print the set at the end

In [6]:
list_of_numbers = [1, 6, 2, 7, 2]
# Write your code below
my_even_set = set()
for i in list_of_numbers:
    if i%2 == 0:
        my_even_set.add(i)

print(my_even_set)

{2, 6}

Exercise: Use a `for` loop to combine all the words in the following list. Then, build a set from the letters and use it to count the number of unique letters in the list

In [ ]:
my_list = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
# Write your code below

### Range

The `range` function is commonly used in `for` loops. `range(my_int)` returns an iterator that goes from 0 to `my_int - 1`. It is similar to a list but not exactly the same.

In [8]:
for i in range(5):
    print(i)

0
1
2
3
4

In [9]:
list(range(5))

[0, 1, 2, 3, 4]

It can also take additional arguments. `range(start, end)` returns an iterator from `start` to `end - 1` inclusive, and `range(start, end, step)` returns a similar iterator, but increments by `step` instead of 1

In [10]:
for i in range(2, 7):
    print(i)

2
3
4
5
6

In [11]:
for i in range(2, 13, 4):
    print(i)

2
6
10

This is very useful when we want to perform an action a fixed number of times

In [12]:
for i in range(5):
    print("I want to print this five times")

I want to print this five times
I want to print this five times
I want to print this five times
I want to print this five times
I want to print this five times

Or when we want to iterate over a list

In [13]:
my_list = [4, 2, 7, 3, 7, 3]
for i in range(len(my_list)):
    print(i, my_list[i])

0 4
1 2
2 7
3 3
4 7
5 3

Exercise: Use `for` loops to sum the numbers in the following list

In [14]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Write your code below
sum = 0
for i in my_list:
    sum += i
print(sum)

45

Exercise: Use `for` loops and `range` to sum the numbers from 1 to 9 inclusive

In [16]:
# Write your code below
sum = 0
for i in range(1, 10):
    sum = sum + i
print(sum)

45

Exercise: Use for loops and range to sum the cubes of the odd numbers between 1 and 9 inclusive

In [18]:
# Write your code below
sum = 0
for i in range(1, 10):
    if i%2 != 0:
        sum = sum + i**3
print(sum)

1225

Exercise: Print a right handed right triangle of height 10. A right handed right triangle of height 3 looks like

```
  *
 **
***
```

In [ ]:
# Write your code below

Exercise: Use `for` loops and `range` to calculate the 15th Fibonacci number.

The zeroth and first Fibonacci numbers are 0 and 1, and every Fibonacci number thereafter is the sum of the previous two Fibonacci numbers. So, the sequence starts off like:

0, 1, 1, 2, 3, 5, ...

In [ ]:
# Write your code below
a = 1 # odd sequence
b = 1 # even sequence
odd = True
for i in range(int(input("Sequence number: "))-2):
  if odd == True:
    a = a + b
    odd = False
  else:
    b = a + b
    odd = True

if odd == False:
  print(a)
if odd == True:
  print(b)

### While loops

Sometimes, we don't know the number of loops we want to do beforehand, which makes it difficult to use a `for` loop. Instead, we might want to do something as long as a certain condition is `True`, which is where `while` loops come in. Be careful though, if the condition is never broken, your code will get stuck in an infinite loop. 

The syntax is similar to an `if`statement, and looks like

```
while condition:
    code to be executed while the condition is True

code that will be executed afterwards
```
For example, lets print the value of our variable and add 5 while it is less than 20

In [19]:
a = 2
while a < 20:
    print(a)
    a += 5

2
7
12
17

Exercise: Use a while loop to print the numbers from 1 to 10

In [20]:
# Write your code below
loops = 1
while loops <= 10:
    print(loops)
    loops += 1

1
2
3
4
5
6
7
8
9
10

### `break`, `continue`, `pass`

`break`, `continue`, and `pass` are three special statements that can be used to manipulate loop logic. `break` will exit a loop immediately. For example, we can use this to stop the following loop when `i` is equal to 2, instead of iterating through 5.

In [21]:
for i in range(5):
    print(i)
    if i == 2:
        break

0
1
2

`pass` is used mostly as a placeholder. The inner blocks of an `if` statement or a `for` loops are not allowed to be empty, so if we are not sure what we want to put there we can write `pass` instead

In [24]:
for i in range(5):
    print(i)
    if i == 2:
        # Do something special but we're not sure yet
        pass

0
1
2
3
4

`continue` skips the rest of the current loop and moves onto the next loop. Here hello is printed after every number except for 2, because when `i` is equal to 2 the second print statement is skipped.

In [25]:
for i in range(5):
    print(i)
    if i == 2:
        continue
    print("hello")

0
hello
1
hello
2
3
hello
4
hello

## Functions

When writing code, you'll find that you will want to do a similar operation repeatedly. For example, suppose that you are converting temperatures from Fahrenheit to Celsius

The conversion formula is

`C = (F - 32)*5/9`

where C is the temperature in Celsius and F is the temperature in Fahrenheit. We could write this every time we need to convert the temperature, but if we mistype or otherwise make a mistake anywhere, it would be very difficult detect or isolate the error. So, instead we write a function that performs this operation. The syntax for a function is as follows

```
def my_function_name(input_1, input_2, input_3, ...):
    do stuff with inputs
    return my_return_value
```
To use the function, simply call it with the values you want
```
my_function_name(val_1, val_2, val_3, ...)
```
So, a function that does the above conversion might look like this

In [5]:
def convert_to_celsius(temp_in_fahrenheit):
    temp_in_celsius = (temp_in_fahrenheit - 32)*5/9
    return temp_in_celsius

print(convert_to_celsius(32))
print(convert_to_celsius(212))
print(convert_to_celsius(-40))

0.0
100.0
-40.0

Functions can take multiple inputs, or no inputs at all. They can return lists, tuples, or nothing at all.

In [7]:
def adds_two_numbers(num_1, num_2):
    return num_1 + num_2

def say_hello():
    print("hello")
    return None

def adds_subtracts_and_multiplies(num_1, num_2):
    return [num_1 + num_2, num_1 - num_2, num_1*num_2]

x = say_hello()

9
hello
None
[9, -1, 20]

In [1]:
def my_function(i):
    i += 1
    print(i)

In [2]:
my_function(5)

6

In [12]:
my_global = 0

def my_function():
    global my_global
    my_global +=1
    # do other stuff

my_function()

print(my_global)

1

Exercise: Write a function that takes a string as input, then repeats it three times with spaces in between. For example, if the input is "Yarn", the output should be "Yarn Yarn Yarn"

In [13]:
# Write your code below
def repeat_three_times(input_string):
    return input_string + " " + input_string + " " + input_string

In [15]:
repeat_three_times("Yarn")

'Yarn Yarn Yarn'

Exercise: Given a integer input `k`, print `*`'s in an isosceles triangle of height `k`. For example, given 3, print


```
  *
 ***
*****
```

In [ ]:
# Write your code below

Exercise: Write a function that takes a positive integer `k` as input, then returns the `k`th Fibonacci number

In [ ]:
# Write your code below

## Modules

Of course, many functions have already been written before, and it would be very inefficient to have to write everything from scratch yourself every time. We can use other people's code by importing them as packages and modules. There are several ways to do this; as an example suppose we want to use the `sqrt` function from the `math` module

The basic syntax is as follows: we import the module and use its functions by prefixing the function with the module name, separated by a dot
```
import math
math.sqrt(2)
```
If we don't want to have to write out `math` every time we use a function from that module, we can create our own name for the module
```
import math as m
m.sqrt(2)
```
Alternatively, if we only want the specific function `sqrt` from the math module, we can import just that function and not have to use any prefixes
```
from math import sqrt
sqrt(2)
```

Exercise: Use the `gcd` function from the `math` module to calculate the gcd of `1634614` and `1234014380`

In [16]:
# Write your code below
import math
math.gcd(1634614, 1234014380)

58

### Packages
Modules can be organized into packages, which introduces a hierarchical structure. The NumPy package is a very useful package in Python, and contains many modules. One such module is the `random` module, which contains a function called `randint`, which generates a random integer between 0 and your input. There are several different ways to access this function to generate a number between 0 and 5.

```
import numpy as np
np.random.randint(5)
```

```
from numpy import random
random.randint(5)
```

```
from numpy.random import randint
randint(5)
```

These are the most common ways to access a function in a package, but by no means is this list exhaustive.

Exercise: Use the `rand` function from the `random` module in `numpy` to generate a random number between 0 and 1.

In [19]:
# Write your code below
import numpy as np
np.random.rand()

0.489403461515459

Exercise: Use the `rand` function from the `random` module in `numpy` to generate a 2 by 2 matrix where each entry is a random number between 0 and 1

In [ ]:
# Write your code below

In [21]:
x = 1
print(x)
x = +5
print(x)

1
5